[package]
name = "castaway"
version = "0.1.0"
authors = ["Nikita Pekin <contact@nikitapek.in>"]

[dependencies]
futures = "0.1.25"
grpc = "0.5.0"
protobuf = "2.1.1"
tls-api = "0.1.20"
tls-api-native-tls = "0.1.20"

[build-dependencies]
protoc-rust-grpc = "0.5.0"
