[package]
name = "castaway"
version = "0.1.0"
authors = ["Nikita Pekin <contact@nikitapek.in>"]

[dependencies]
libc = "0.2.44"
rand = "0.5.5"

[build-dependencies]
cbindgen = {version = "0.6.7", optional = true}
