version: '3'

services:
    castaway_1:
        build: .
        ports:
          - 58051:58051
        volumes:
          - .:/usr/src/castaway
        command: target/debug/castaway --tls --id 1 --address 127.0.0.1 --port 58051 --peer tcp://127.0.0.1:58051 --peer tcp://127.0.0.1:58052
    castaway_2:
        build: .
        ports:
          - 58052:58052
        volumes:
          - .:/usr/src/castaway
        command: target/debug/castaway --tls --id 2 --address 127.0.0.1 --port 58052 --peer tcp://127.0.0.1:58051 --peer tcp://127.0.0.1:58052
